name: Develop branch pipeline

on:
  push:
    branches:
      - 'develop-*'
  pull_request:
    branches:
      - 'develop-*'

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.reusable.yml
  build-and-publish:
    # if: ${{ github.event_name == 'push' }}
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Parse semver string
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.branch-name.outputs.current_branch }}
          version_extractor_regex: '.*develop-(.*)$'
      - name: Show semver string
        shell: bash
        run: echo "Detected semver ${{ steps.semver_parser.outputs.fullversion }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            jonfelixrico/wisdom-panel-server
          tags: |
            alpha-${{ steps.semver_parser.outputs.major }}
            alpha-${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
